### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by hohwille** [m-m-m/cli#1]
see CI build
Problem not reproducible in IDE, as always some java platform module system bug as I am one of the only ones using it on a larger scale. I assume resource bundles from l10n can not be found due to classpath vs. modulepath issues...
```
expected: 
  "42
  "
 but was: 
  ""
```

I assume that an exception was thrown and as the CLI tests are streaming this in a memory buffer, it never shows up on the logs.
Cool, I get three different results:
* Eclipse all tests succeed
* local maven call, error with detailed stacktrace
* github assertion error without the actual stacktrace

**Comment by hohwille** [comment]
I changed to soft assertions but still I get the same feedback:
Exit code matches and nothing is printed to standard error but also standard out is empty so program output is missing.
That is mystical - I assume that an exception is happening but somehow does not make it into the error output.
Maybe a buggy JDK in github action, will have to keep on trying...

**Comment by hohwille** [comment]
Locally I get this on the console via maven while Eclipse is not giving me any errors when I run the test:
```
Multiple Failures (3 failures)
-- failure 1 --
expected: ""
 but was: "ERROR: An unexpected error has occurred.
java.util.MissingResourceException: Can't find bundle for base name l10n.io.github.mmm.nls.cli.CliCommandHelp, locale en_US
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1575)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
        at io.github.mmm.nls.cli@0-SNAPSHOT/io.github.mmm.nls.cli.CliBundle.<init>(CliBundle.java:29)
        at io.github.mmm.nls.cli@0-SNAPSHOT/io.github.mmm.nls.cli.CliBundle.of(CliBundle.java:81)
        at io.github.mmm.nls.cli@0-SNAPSHOT/io.github.mmm.nls.cli.CliCommandHelp.run(CliCommandHelp.java:34)
        at java.base/java.lang.reflect.InvocationHandler.invokeDefault(InvocationHandler.java:286)
        at io.github.mmm.bean.factory@0-SNAPSHOT/io.github.mmm.bean.factory.impl.operation.BeanOperation.invokeDefaultMethod(BeanOperation.java:62)
        at io.github.mmm.bean.factory@0-SNAPSHOT/io.github.mmm.bean.factory.impl.operation.BeanOperationDefaultMethod.invoke(BeanOperationDefaultMethod.java:33)
        at io.github.mmm.bean.factory@0-SNAPSHOT/io.github.mmm.bean.factory.impl.proxy.BeanProxy.invoke(BeanProxy.java:80)
        at jdk.proxy2/jdk.proxy2.$Proxy11.run(Unknown Source)
        at io.github.mmm.nls.cli@0-SNAPSHOT/io.github.mmm.nls.cli.NlsMain.run(NlsMain.java:171)
        at io.github.mmm.cli@0-SNAPSHOT/io.github.mmm.cli.CliMain.run(CliMain.java:150)
        at io.github.mmm.nls.cli@0-SNAPSHOT/io.github.mmm.nls.cli.NlsMainTest.assertProgram(NlsMainTest.java:100)
        at io.github.mmm.nls.cli@0-SNAPSHOT/io.github.mmm.nls.cli.NlsMainTest.assertProgram(NlsMainTest.java:84)
        at io.github.mmm.nls.cli@0-SNAPSHOT/io.github.mmm.nls.cli.NlsMainTest.testHelp(NlsMainTest.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
"
at NlsMainTest.assertProgram(NlsMainTest.java:103)
-- failure 2 --
expected: "Usage:
io.github.mmm.nls.cli.TestProgram --help|-h
Print this help.

io.github.mmm.nls.cli.TestProgram --version|-v
Print the version of this program.

io.github.mmm.nls.cli.TestProgram --mode|-m <mode> <value>
Test the command-line-interface.

Required options:
  --mode|-m  Mode of test.

Parameters:
  value  Value of test.

JVM options:
  -Duser.language  The locale for translation (e.g. '-Duser.language=de' for German).
  -Xmx             The maximum heap size (e.g. '-Xmx8G' for 8 gigabyte of heap memory).
  -Xloggc          Writes all garbage collector activity to the specified logfile (e.g. '-Xloggc:/home/user/log/gc.log').
"
 but was: ""
at NlsMainTest.assertProgram(NlsMainTest.java:104)
-- failure 3 --
expected: 0
 but was: -1
at NlsMainTest.assertProgram(NlsMainTest.java:105)
```

**Comment by hohwille** [comment]
The resource bundle for `l10n.io.github.mmm.nls.cli.CliCommandHelp` is definitely present and in Eclipse I can even translate to German and get the expected output. So what ever Java is doing here I am not yet getting it.

**Comment by hohwille** [comment]
At least now I get the same errors in github action as locally in commandline.
Next I have to see why JPMS is not able to load the resource bundle.
It should actually be present:
https://github.com/m-m-m/l10n/blob/master/en/src/main/resources/l10n/io/github/mmm/nls/cli/CliCommandHelp.properties

**Comment by hohwille** [comment]
OK, I now have traced down the error and it goes down to JPMS that prevents loading the `l10n` JARs even though they are not modules causing this warning message:
```
[WARNING] Can't extract module name from mmm-l10n-de-0-SNAPSHOT.jar: mmm.l10n.de.0.SNAPSHOT: Invalid module name: '0' is not a Java identifier
[WARNING] Can't extract module name from mmm-l10n-all-0-SNAPSHOT.jar: mmm.l10n.all.0.SNAPSHOT: Invalid module name: '0' is not a Java identifier
[WARNING] Can't extract module name from mmm-l10n-en-0-SNAPSHOT.jar: mmm.l10n.en.0.SNAPSHOT: Invalid module name: '0' is not a Java identifier
[WARNING] Can't extract module name from mmm-l10n-fr-0-SNAPSHOT.jar: mmm.l10n.fr.0.SNAPSHOT: Invalid module name: '0' is not a Java identifier
[WARNING] Can't extract module name from mmm-l10n-es-0-SNAPSHOT.jar: mmm.l10n.es.0.SNAPSHOT: Invalid module name: '0' is not a Java identifier
```

So when I run the build of the entire project it fails here but when I run the same build with `-Drevision=1.2.3` it is successful.
Because of JPMS I already have changed from `dev-SNAPSHOT` to `0-SNAPSHOT` but it seems that this did not solve the real problem. The build is also successful with `-Drevision=1.2.3-SNAPSHOT` or `-Drevision=0.0-SNAPSHOT` so I can now fix this but have to change all POMs in all repositories.

**Comment by hohwille** [comment]
finally fixed
